### ISSUE TITLE
 index run is failure in testnet

### ISSUE THREAD

**Issue by softwarecheng** [bestinslot-xyz/OPI#4]
The process is as follows:
1 configure FIRST_INSCRIPTION_HEIGHT="2413343" in .env (the first inscription of testnet)
2 make the last command of ord in index.js become:
```shell
ord --chain testnet --cookie-file ./testnet3/.cookie --bitcoin-data-dir ./testnet3 --rpc-url address:port --data-dir ./orddata/ --height-limit 2413843 index run
```
3 when running to a height above 242000 and then continuing, a prompt will appear:
```shell
Index file "xxx/index.redb" needs recovery. This can take a long time, especially for the --index-sats index.
```
4 try to increase the memory and restart the Linux and bitcoind services, but the same result is obtained.

5 Also try using --index-sats
```shell
export RUST_BACKTRACE=1
ord --chain testnet --cookie-file ./testnet3/.cookie --bitcoin-data-dir ./testnet3 --rpc-url address:port --data-dir ./orddata/ --height-limit 2413843  --index-sats index run is in progress. An error will be encountered during the process and cannot be continued. The error is as follows:
thread 'main' panicked at 'assertion failed: `(left == right)`
   left: `1`,
  right: `0`', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/redb-1.1.0/src/tree_store/page_store/region.rs:312:9
stack backtrace:
    0: rust_begin_unwind
              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
    1: core::panicking::panic_fmt
              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
    2: core::panicking::assert_failed_inner
    3: core::panicking::assert_failed
    4: redb::tree_store::page_store::region::Allocators::from_bytes
    5: redb::tree_store::page_store::page_manager::InMemoryState::from_bytes
    6: redb::tree_store::page_store::page_manager::TransactionalMemory::new
    7: redb::db::Database::new
    8: redb::db::Builder::open
    9: ord::index::Index::open
   10: ord::subcommand::index::IndexSubcommand::run
   11: ord::subcommand::Subcommand::run
   12: ord::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
ERROR ON ORD!!!
```

**Comment by samedcildir** [comment]
Currently testnet is not supported but its on our backlog, it'll probably be added next week
